# docker-compose.yml
services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=bluesoft
      - POSTGRES_PASSWORD=bluesoft
      - POSTGRES_DB=bluesoft_bank
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres:
